name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Execute all scripts
        run: .github/workflows/run-all-scripts.sh
